dist: trusty
language: node_js
node_js:
  - "12"
addons:
  chrome: stable
before_install:
  - "google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
jobs:
  include:
	- name: "Lint"
	  script: npm run lint
	- name: "Test"
	  script: npm test
script: npm run ng:build
deploy:
  provider: script
  script: "bash ./scripts/deploy.sh"
  skip_cleanup: true
  on:
    all_branches: true
notifications:
  email: false
